import { useEffect, useState } from "react";
import { getAssessmentGenerator, saveAssessmentGenerator } from "../../services/recruiterService";
import LoadingState from "../../components/common/LoadingState";
import BackButton from "../../components/common/BackButton";

const tagColors = { default: { bg: "#F3F4F6", color: "#374151" }, success: { bg: "#D1FAE5", color: "#065F46" }, danger: { bg: "#FEE2E2", color: "#991B1B" }, primary: { bg: "#EDE9FE", color: "#6D28D9" } };

export default function AssessmentGeneratorPage() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    getAssessmentGenerator().then(setData).finally(() => setLoading(false));
  }, []);

  const handleSave = async () => {
    setSaving(true);
    try {
      await saveAssessmentGenerator(data);
    } finally {
      setSaving(false);
    }
  };

  if (loading) return <LoadingState message="Loading assessment generator..." />;
  if (!data) return null;

  return (
    <>
      <BackButton fallbackTo="/recruiter/dashboard" label="Back to Dashboard" />
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 28 }}>
        <div>
          <span className="ai-badge mb-2 d-inline-flex"><i className="bi bi-stars" /> AI-Powered Generation</span>
          <h1 style={{ fontSize: 26, fontWeight: 800, marginBottom: 4 }}>Assessment Generator</h1>
          <p style={{ color: "var(--text-muted)", margin: 0 }}>Review and refine the questions generated by HireAI for the {data.jobTitle} position.</p>
        </div>
        <div style={{ display: "flex", gap: 10 }}>
          <button type="button" className="btn-outline-custom" style={{ fontSize: 13 }}><i className="bi bi-arrow-clockwise me-2" />Regenerate Questions</button>
          <button type="button" className="btn-primary-custom" style={{ fontSize: 13 }} onClick={handleSave} disabled={saving}>
            <i className="bi bi-save me-2" />{saving ? "Saving..." : "Save Assessment"}
          </button>
        </div>
      </div>

      <div style={{ display: "grid", gridTemplateColumns: "1fr 300px", gap: 20 }}>
        <div>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}>
            <div style={{ fontWeight: 700 }}>Generated AI Questions</div>
            <span style={{ background: "var(--primary-bg)", color: "var(--primary)", fontSize: 12, fontWeight: 700, padding: "4px 10px", borderRadius: 20 }}>
              {data.questionCount} Questions Generated
            </span>
          </div>
          <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
            {data.questions.map((q) => (
              <div key={q.id} className="hcard" style={{ padding: 20 }}>
                <div style={{ fontSize: 12, color: "var(--text-muted)", fontWeight: 700, marginBottom: 8 }}>Question {String(q.number).padStart(2, "0")}</div>
                <p style={{ fontWeight: 600, fontSize: 14, lineHeight: 1.6, marginBottom: 12 }}>{q.text}</p>
                <div style={{ display: "flex", gap: 8 }}>
                  {q.tags.map((t) => {
                    const c = tagColors[t.type] || tagColors.default;
                    return <span key={t.label} style={{ background: c.bg, color: c.color, fontSize: 11, fontWeight: 600, padding: "3px 10px", borderRadius: 20 }}>{t.label}</span>;
                  })}
                </div>
              </div>
            ))}
            <button type="button" className="btn-outline-custom w-100" style={{ borderStyle: "dashed" }}>
              <i className="bi bi-plus me-2" />Add Custom Question
            </button>
          </div>
        </div>

        <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
          <div className="hcard" style={{ padding: 20 }}>
            <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 16 }}>
              <i className="bi bi-gear" style={{ color: "var(--primary)" }} aria-hidden="true" />
              <span style={{ fontWeight: 700 }}>Assessment Settings</span>
            </div>
            <div style={{ marginBottom: 14 }}>
              <label style={{ fontSize: 12, fontWeight: 600, marginBottom: 6, display: "block" }}>Duration (Minutes)</label>
              <select className="form-select" defaultValue={data.duration} style={{ fontSize: 14, borderRadius: 10 }}>
                <option>{data.duration}</option>
                <option>30 Minutes</option>
                <option>60 Minutes</option>
              </select>
            </div>
            <div style={{ marginBottom: 14 }}>
              <label style={{ fontSize: 12, fontWeight: 600, marginBottom: 6, display: "block" }}>Total Marks</label>
              <input className="form-control" defaultValue={data.totalMarks} style={{ borderRadius: 10, fontSize: 14 }} />
            </div>
            <div>
              <label style={{ fontSize: 12, fontWeight: 600, marginBottom: 6, display: "block" }}>Passing Threshold (%)</label>
              <div style={{ fontSize: 28, fontWeight: 800, color: "var(--primary)" }}>{data.passingThreshold}%</div>
            </div>
          </div>

          <div className="hcard" style={{ padding: 20, background: "var(--primary-bg)", border: "1px solid #DDD6FE" }}>
            <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 10 }}>
              <i className="bi bi-stars" style={{ color: "var(--primary)" }} aria-hidden="true" />
              <span style={{ fontWeight: 700, fontSize: 13, color: "var(--primary)" }}>AI Generation Logic</span>
            </div>
            <p style={{ fontSize: 12, color: "var(--text-muted)", lineHeight: 1.6, marginBottom: 12 }}>{data.logicNote}</p>
            <div style={{ display: "flex", flexWrap: "wrap", gap: 6 }}>
              {data.skillTags.map((t) => (
                <span key={t} style={{ fontSize: 10, fontWeight: 700, letterSpacing: 0.5, color: "var(--primary)", background: "#fff", padding: "4px 8px", borderRadius: 6 }}>{t}</span>
              ))}
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
